services:
  api:
    build: api
    ports:
      - "6969:6969"
    volumes:
      - persistance:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always
  bot:
    build: bot
    restart: always

volumes:
  persistance:
